name: C CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GCC
        run: sudo apt-get install -y gcc

      - name: Build the project
        run: |
          gcc -o main main.c processing.c io.c unit_tests.c
          echo "Build successful"

      - name: Run unit tests
        run: |
          ./main cmake-build-debug/input.txt cmake-build-debug/o.txt
        continue-on-error: false

      - name: Run multiple tests
        run: |
          STATUS=0
          for i in {1..7}; do
            echo "Running test case $i"
            if ./main tests/input_$i.txt tests/output_$i.txt; then
              if [[ $i -ge 4 && $i -le 7 ]]; then
                echo "Test case $i expected to fail but succeeded. Marking as failure."
                STATUS=1
              else
                echo "Test case $i completed successfully."
                if ! diff tests/output_$i.txt tests/test_output_$i.txt; then
                  echo "Test case $i failed: Output does not match expected!"
                  STATUS=1
                fi
              fi
            else
              if [[ $i -ge 4 && $i -le 7 ]]; then
                echo "Test case $i failed as expected."
              else
                echo "Test case $i failed unexpectedly. Marking as failure."
                STATUS=1
              fi
            fi
          done
          exit $STATUS
